services:
  yolov8_app:
    build:
      context: ./yolov8_app/
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./yolov8_app
          target: /app
    ports:
      - 8501:8501
      - 8000:8000
    restart: always
    container_name: myinvictia_yolov8_app
# The following lines are here to enable Nvidia GPU support:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]