version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yolov8-backend
    ports:
      - "8000:8000"
    volumes:
      - original_images:/app/original_images
      - original_videos:/app/original_videos  # Añadiendo volumen de original_videos
      - processed_images:/app/processed_images
      - processed_videos:/app/processed_videos
      - weights:/app/weights
      - ./backend/main.py:/app/main.py
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: yolov8-frontend
    ports:
      - "8501:8501"
    volumes:
      - original_images:/app/original_images
      - original_videos:/app/original_videos  # Añadiendo volumen de original_videos
      - processed_images:/app/processed_images
      - processed_videos:/app/processed_videos
      - ./frontend/streamlit_app.py:/app/streamlit_app.py
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M

volumes:
  original_images:
  original_videos:  # Añadiendo volumen de original_videos
  processed_images:
  processed_videos:
  weights: