services:
  yolov8_app:
    build:
      context: ./yolov8_app/
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./yolov8_app
          target: /app
    ports:
      - 8501:8501
      - 8000:8000
    restart: always
    container_name: myinvictia_yolov8_app