version: '3.8'

services:
  yolov8_app:
    build:
      context: ./yolov8_app/
      dockerfile: Dockerfile
    volumes:
      - ./yolov8_app/:/app/
    ports:
      - 8501:8501
      - 8000:8000
    restart: always
# Uncomment the following lines to enable GPU support:
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]